name: build and push to dockerhub

on:
  push:
    branches:
      - 'main'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: oussemaloukil/praccforces:latest
          
      - name: Build and Push ARM Image
        uses: docker/build-push-action@v4
        with:
          platforms: linux/arm64
          push: true
          tags: oussemaloukil/praccforces:latest
